// type
const CODE_TEST = 'TEST';
const CODE_GENERAL_NOTIFY_MAILS = 'GENERAL_NOTIFY_MAILS';
const CODE_PROJECT_ABOUT_HTML = 'PROJECT_ABOUT_HTML';
const CODE_PROJECT_DEVELOPERS_JSON = 'PROJECT_DEVELOPERS_JSON';

exports.CODE_TEST = CODE_TEST;
exports.CODE_GENERAL_NOTIFY_MAILS = CODE_GENERAL_NOTIFY_MAILS;
exports.CODE_PROJECT_ABOUT_HTML = CODE_PROJECT_ABOUT_HTML;
exports.CODE_PROJECT_DEVELOPERS_JSON = CODE_PROJECT_DEVELOPERS_JSON;
exports.CODE_ALL = [
  CODE_TEST,
  CODE_GENERAL_NOTIFY_MAILS,
  CODE_PROJECT_ABOUT_HTML,
  CODE_PROJECT_DEVELOPERS_JSON,
];
