// type
const CODE_TEST = 'TEST';
const CODE_GENERAL_NOTIFY_MAILS = 'GENERAL_NOTIFY_MAILS';

exports.CODE_TEST = CODE_TEST;
exports.CODE_GENERAL_NOTIFY_MAILS = CODE_GENERAL_NOTIFY_MAILS;
exports.CODE_ALL = [CODE_TEST, CODE_GENERAL_NOTIFY_MAILS];
