// Load state
export const GL_PRODUCT_LOADED = 'GL_PRODUCT_LOADED';
export const GL_PRODUCT_LOADING = 'GL_PRODUCT_LOADING';
export const GL_PRODUCT_LOADING_ERROR = 'GL_PRODUCT_LOADING_ERROR';

// Add
export const GL_PRODUCT_ADDED = 'GL_PRODUCT_ADDED';
export const GL_PRODUCT_ADDING = 'GL_PRODUCT_ADDING';
export const GL_PRODUCT_ADDING_ERROR = 'GL_PRODUCT_ADDING_ERROR';
